package com.dao.generate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AREA".
 */
public class Area {

    private Long id;
    private int areaId;
    /** Not-null value. */
    private String name;
    private int parentId;
    private int cityId;

    public Area() {
    }

    public Area(Long id) {
        this.id = id;
    }

    public Area(int areaId, String name, int parentId, int cityId) {
        this.areaId = areaId;
        this.name = name;
        this.parentId = parentId;
        this.cityId = cityId;
    }

    public Area(Long id, int areaId, String name, int parentId, int cityId) {
        this.id = id;
        this.areaId = areaId;
        this.name = name;
        this.parentId = parentId;
        this.cityId = cityId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAreaId() {
        return areaId;
    }

    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getParentId() {
        return parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public int getCityId() {
        return cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

}
