package com.dao.generate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.dao.base.BaseSortFilterModel;

import java.io.Serializable;

/**
 * Entity mapped to table "AREA".
 */
public class Area extends BaseSortFilterModel<Area> implements Serializable {

    private Long id;
    private int areaId;
    /**
     * Not-null value.
     */
    private String name;
    private int parentId;
    private int cityId;

    public Area() {
    }

    public Area(Long id) {
        this.id = id;
    }

    public Area(int areaId, String name, int parentId, int cityId) {
        this.areaId = areaId;
        this.name = name;
        this.parentId = parentId;
        this.cityId = cityId;
    }

    public Area(Long id, int areaId, String name, int parentId, int cityId) {
        this.id = id;
        this.areaId = areaId;
        this.name = name;
        this.parentId = parentId;
        this.cityId = cityId;
    }

    public Area(int areaId, String name, int parentId) {
        this.areaId = areaId;
        this.name = name;
        this.parentId = parentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAreaId() {
        return areaId;
    }

    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    public int getParentId() {
        return parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public int getCityId() {
        return cityId;
    }

    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    @Override
    public int getFilterId() {
        return areaId;
    }

    @Override
    public int getFilterParentId() {
        return parentId;
    }

    @Override
    public String getFilterName() {
        return name;
    }

    @Override
    public Area getAllFirstFilter() {
        return new Area(ALL_FILTER_ID, "全城", INVALID_PARENT_ID);
    }

    @Override
    public Area getAllSubFilter(int parentFilterId) {
        if (parentFilterId == NearbyArea.NEARBY_ID)//附近的不需要全部item
            return null;
        return new Area(ALL_FILTER_ID, ALL_FILTER_NAME, parentFilterId);
    }
}
