package com.dao.generate;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dao.generate.City;
import com.dao.generate.Area;
import com.dao.generate.Category;

import com.dao.generate.CityDao;
import com.dao.generate.AreaDao;
import com.dao.generate.CategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig areaDaoConfig;
    private final DaoConfig categoryDaoConfig;

    private final CityDao cityDao;
    private final AreaDao areaDao;
    private final CategoryDao categoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Area.class, areaDao);
        registerDao(Category.class, categoryDao);
    }
    
    public void clear() {
        cityDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

}
